development:
  adapter: postgresql
  encoding: utf-8
  database: quiz #lbr_jsonb_local3 #nine_dot_nine_sep19
  host: localhost
  username: postgres
  password: postgres
  port: 5432

production:
  adapter: postgresql
  encoding: utf-8
  database: quiz #lbr_jsonb_local3 #nine_dot_nine_sep19
  host: localhost
  username: postgres
  password: postgres
  port: 5432

